// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7aIUluBjrJ_r0XTN8cmC60QOm_bO4Auc',
    appId: '1:237321230270:web:30f956467f54f6dafe4bef',
    messagingSenderId: '237321230270',
    projectId: 'sttg-ac2a3',
    authDomain: 'sttg-ac2a3.firebaseapp.com',
    storageBucket: 'sttg-ac2a3.appspot.com',
    measurementId: 'G-ZF4TC4KXRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUec5hLkoCUKuOJqi5DLgGAyOm_uev-fI',
    appId: '1:237321230270:android:4e1bb49ae39b7dc1fe4bef',
    messagingSenderId: '237321230270',
    projectId: 'sttg-ac2a3',
    storageBucket: 'sttg-ac2a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnXFmmfHV2AOr8KEIbUsV6oT2UlBIjrPE',
    appId: '1:237321230270:ios:769c04bd04419685fe4bef',
    messagingSenderId: '237321230270',
    projectId: 'sttg-ac2a3',
    storageBucket: 'sttg-ac2a3.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnXFmmfHV2AOr8KEIbUsV6oT2UlBIjrPE',
    appId: '1:237321230270:ios:b6653df73effbc50fe4bef',
    messagingSenderId: '237321230270',
    projectId: 'sttg-ac2a3',
    storageBucket: 'sttg-ac2a3.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
